### ISSUE TITLE
EMail after shipment complete, send email to customer that order was shipped

### ISSUE THREAD

**Issue by e0725439** [e0725439/ac.at.tuwien.s2015.wmpm.g13#20]

**Comment by pppppp1** [comment]
Finished for the case that every order item is in stock.

**Comment by pppppp1** [comment]
TODO:
Send email after stocks are replenished

**Comment by nathaniel-boisgard** [comment]
I have created a new branch with the functionality to send the email (wmpm_20-2) and am currently working on this if its OK with y'all

**Comment by nathaniel-boisgard** [comment]
für die würste!

**Comment by nathaniel-boisgard** [comment]
Use seda queue, can be found in seda:shipment-email.queue
